apiVersion: apps/v1
kind: Deployment
metadata:
  name: astonvilla-app
spec:
  selector:
    matchLabels:
      app: astonvilla-app
  template:
    metadata:
      labels:
        app: astonvilla-app
    spec:
      containers:
        - name: astonvilla-app
          image: oumaimakhelifi/astonvilla-app:1.1.36
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
         
