
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-pv
spec:
  capacity:
    storage: "100Mi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Replaced 'Recycle' with 'Retain'
  storageClassName: "manual"
  hostPath:
    path: "/mnt/index"
  # Optionally, you can add labels to match the PVC:
  labels:
    type: local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-pvc
spec:
  resources:
    requests:
      storage: "100Mi"
  volumeMode: Filesystem
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-pvc
spec:
  replicas: 1  # It's good practice to explicitly define the number of replicas
  selector:
    matchLabels:
      app: pv-pvc
  template:
    metadata:
      labels:
        app: pv-pvc
    spec:
      volumes: 
        - name: data
          persistentVolumeClaim:
            claimName: hello-pvc
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
