apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-pvc
spec:
  resources:
    requests:
      storage: "100Mi"
  volumeMode: Filesystem
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
